name: JellyCar II build
on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target Platform (Win32 or x64)'
        default: 'x64'
        required: true
      configuration:
        description: 'Target Configuration (Debug or Release)'
        default: 'Release'
        required: true
      andromeda_repo:
        description: 'Andromeda-Lib Repository (DrakonPL/Andromeda-Lib)'
        default: 'DrakonPL/Andromeda-Lib'
        required: true

jobs:
  build:
    runs-on: windows-latest
    
    # Environment variables derived from inputs and logic
    env:
      SOLUTION_FILE: JellyCar.sln
      PLATFORM: ${{ github.event.inputs.platform || 'x64' }}
      CONFIGURATION: ${{ github.event.inputs.configuration || 'Release' }}
      # Crucial: Define a clean build directory for the dependencies
      ANDROMEDA_CLONE_PATH: 'ANDROMEDA_CLONED'

    steps:
    
    # 1. SETUP BUILD TOOLS
    - name: Install MSVC Build Toolset (v142)
      uses: microsoft/setup-msbuild@v2 
      with:
        msbuild-toolset: 'v142' 

    # 2. CLONE DEPENDENCY: Andromeda-Lib 
    - name: 1. Clone Andromeda-Lib Dependency
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.inputs.andromeda_repo }}
        path: ${{ env.ANDROMEDA_CLONE_PATH }}
        
    # 3. CLONE SOURCE: JellyCar-II Repository
    - name: 2. Clone JellyCar-II Source Code
      uses: actions/checkout@v4
      with:
        path: JellyCar-Source # The folder containing the main JellyCar.sln

    # 4. FIX RELATIVE PATHS FOR COMPILATION
    - name: Pre-build Prep & Copy Assets
      run: |
        # Ensure solution and project files are correctly named at the JellyCar root
        Move-Item JellyCar_sln.txt JellyCar-Source/$env:SOLUTION_FILE
        Move-Item JellyCar_vcxproj.txt JellyCar-Source/JellyCar.vcxproj

        # ***CRITICAL: Copy Andromeda Lib into the expected directory structure***
        # We assume the user structure looks like this for MSBuild to find the paths like 
        # "..\\..\\..\\..\\Andromeda-Lib\\..." which the project file uses.
        
        # We must MOVE the cloned Andromeda repo so its structure resolves the ..\..\..\..\ path
        Move-Item $env:ANDROMEDA_CLONE_PATH/Build JellyCar-Source/Build

    # 5. BUILD DEPENDENCY: Build Andromeda.vcxproj First
    - name: Build Andromeda Dependency (REQUIRED)
      working-directory: 'JellyCar-Source\Build\Windows\Andromeda'
      run: |
        # Use the GUID of the Andromeda project {CDD70FEF-A453-450C-813C-E7ADFC640A24} 
        # to ensure the build only targets this library first
        msbuild Andromeda.vcxproj /t:Build /p:Configuration=$env:CONFIGURATION /p:Platform=Win32

    # 6. COMPILE THE GAME: Build JellyCar Project
    - name: Compile JellyCar Project (Using MSBuild)
      # Execution directory needs to be the Solution File root
      working-directory: 'JellyCar-Source'
      run: |
        msbuild "$env:SOLUTION_FILE" /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM
        
    # 7. ARCHIVE THE EXECUTABLE
    - name: Archive Compiled Executable
      uses: actions/upload-artifact@v4
      with:
        name: JellyCar-Build-${{ env.PLATFORM }}-${{ env.CONFIGURATION }}
        # The probable final output path for the executable after successful linking:
        path: |
          JellyCar-Source\${{ env.CONFIGURATION }}\JellyCar.exe
