name: Bob the Builder

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Target Platform (Win32 or x64)'
        default: 'x64'
        required: true
      configuration:
        description: 'Target Configuration (Debug or Release)'
        default: 'Release'
        required: true
      andromeda_repo:
        description: 'Andromeda-Lib Repository (DrakonPL/Andromeda-Lib)'
        default: 'DrakonPL/Andromeda-Lib'
        required: true

jobs:
  build:
    runs-on: windows-latest
    
    env:
      PLATFORM: ${{ github.event.inputs.platform || 'x64' }}
      CONFIGURATION: ${{ github.event.inputs.configuration || 'Release' }}

    steps:
    
    # 1. SETUP BUILD TOOLS
    - name: Install MSVC Build Toolset (v142)
      uses: microsoft/setup-msbuild@v2 
      with:
        msbuild-toolset: 'v142' 

    # 2. CLONE DEPENDENCY: Andromeda-Lib 
    - name: 1. Clone Andromeda-Lib Dependency
      uses: actions/checkout@v4
      with:
        # Cloned into ./Andromeda-Lib
        repository: ${{ github.event.inputs.andromeda_repo }}
        path: Andromeda-Lib

    # 3. CLONE SOURCE: JellyCar-II Repository
    - name: 2. Clone JellyCar-II Source Code
      uses: actions/checkout@v4
      with:
        # Cloned into ./JellyCar-Source
        path: JellyCar-Source
        
    # 4. CRITICAL PATHING: Building Andromeda first
    - name: Build Andromeda Dependency Project
      # The project path is directly copied from the solution file's GUID association:
      # Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "Andromeda", "..\..\..\Andromeda-Lib\Build\Windows\Andromeda\Andromeda.vcxproj"
      working-directory: './Andromeda-Lib/Build/Windows/Andromeda'
      run: |
        msbuild Andromeda.vcxproj /t:Build /p:Configuration=$env:CONFIGURATION /p:Platform=Win32

    # 5. COMPILE THE GAME: Build JellyCar Project
    - name: Compile JellyCar Project
      # Build the solution in the main source folder where it lives:
      working-directory: './JellyCar-Source'
      run: |
        msbuild JellyCar.sln /p:Configuration=$env:CONFIGURATION /p:Platform=$env:PLATFORM
        
    # 6. ARCHIVE THE EXECUTABLE 
    - name: Archive Compiled Executable
      uses: actions/upload-artifact@v4
      with:
        name: JellyCar-Build-${{ env.PLATFORM }}-${{ env.CONFIGURATION }}
        # The probable final output path for the executable after successful linking:
        path: |
          JellyCar-Source/${{ env.CONFIGURATION }}/JellyCar.exe
